### ISSUE TITLE
Newest VRC SDK Breaks Noclip mod

### ISSUE THREAD

**Issue by NepsyNep** [Varneon/VUdon-Noclip#18]
The Latest Beta SDK for VRC (3.4.0) Changed Udon sharps location into the VRC Worlds Package. Now Noclip Wont compile as it complains about missing udon sharp dependency

**Comment by Varneon** [comment]
Unfortunately I don't have the resources to provide this fix retroactively to existing stable release, but the latest [0.3.0-alpha.2](https://github.com/Varneon/VUdon-Noclip/releases/tag/0.3.0-alpha.2) release is compliant with the new dependency definition.

**Comment by NepsyNep** [comment]
> Unfortunately I don't have the resources to provide this fix retroactively to existing stable release, but the latest [0.3.0-alpha.2](https://github.com/Varneon/VUdon-Noclip/releases/tag/0.3.0-alpha.2) release is compliant with the new dependency definition.

unfortunately the dependency for that version is not available (Alpha 8 udon editor)

**Comment by Varneon** [comment]
> unfortunately the dependency for that version is not available (Alpha 8 udon editor)

Previous dependencies of the **VUdon-Noclip** have been replaced by a new inspector toolkit, [`VUdon-Editors`](https://github.com/Varneon/VUdon-Editors), starting from `0.3.0`.

Please see the updated installation instructions introduced in `0.3.0-alpha.1`:

https://github.com/Varneon/VUdon-Noclip/tree/0.3.0#installation
https://github.com/Varneon/VUdon-Noclip/releases/tag/0.3.0-alpha.1

**Comment by NepsyNep** [comment]
Yes. i seen tthat. but the required dependency for Noclip is Alpha 8 of Vudon editor, your gitup only seems to have alpha 7
So VCC wont install Noclip
